#server:
#  port: 8888
#spring:
#  application:
#    name: xdclass-gateway
#  zipkin:
#    base-url: http://127.0.0.1:9411/ #zipkin地址
#    discovery-client-enabled: false #不⽤开启服务发现
#  sleuth:
#    sampler:
#      probability: 1.0 #采样百分⽐
#
#  cloud:
#    gateway:
#      routes: #数组形式
#      - id: order-service  #路由唯一标识
#        #uri: http://127.0.0.1:9000  #想要转发到的地址
#        uri: lb://xdclass-order-service #从nacos获取名称转发,lb是负载均衡轮训策略
#        order: 1 #优先级，数字越小优先级越高
#        predicates: #断言 配置哪个路径才转发
#        - Path=/order-service/**
##        - Before=2024-12-25T01:01:01.000+08:00
##        - Query=source
#        filters: #过滤器，请求在传递过程中通过过滤器修改
#        - StripPrefix=1  #去掉第一层前缀
#      discovery:
#        locator:
#          enabled: true
#    nacos:
#      discovery:
#        server-addr: 39.105.36.22:8848